/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject3 model module.
 * @module org.wso2.client.model.OnlineMerchant/InlineObject3
 * @version 1.0.0
 */
class InlineObject3 {
    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/InlineObject3
     * @param externalTransactionId {String} 
     * @param referenceNumber {String} 
     */
    constructor(externalTransactionId, referenceNumber) { 
        
        InlineObject3.initialize(this, externalTransactionId, referenceNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, externalTransactionId, referenceNumber) { 
        obj['externalTransactionId'] = externalTransactionId;
        obj['referenceNumber'] = referenceNumber;
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineObject3} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('externalTransactionId')) {
                obj['externalTransactionId'] = ApiClient.convertToType(data['externalTransactionId'], 'String');
            }
            if (data.hasOwnProperty('referenceNumber')) {
                obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} externalTransactionId
 */
InlineObject3.prototype['externalTransactionId'] = undefined;

/**
 * @member {String} referenceNumber
 */
InlineObject3.prototype['referenceNumber'] = undefined;






export default InlineObject3;

