/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200Token model module.
 * @module org.wso2.client.model.OnlineMerchant/InlineResponse200Token
 * @version 1.0.0
 */
class InlineResponse200Token {
    /**
     * Constructs a new <code>InlineResponse200Token</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/InlineResponse200Token
     */
    constructor() { 
        
        InlineResponse200Token.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200Token</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineResponse200Token} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/InlineResponse200Token} The populated <code>InlineResponse200Token</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200Token();

            if (data.hasOwnProperty('expiredAt')) {
                obj['expiredAt'] = ApiClient.convertToType(data['expiredAt'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} expiredAt
 */
InlineResponse200Token.prototype['expiredAt'] = undefined;

/**
 * @member {String} token
 */
InlineResponse200Token.prototype['token'] = undefined;






export default InlineResponse200Token;

