/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2001DataFees from './InlineResponse2001DataFees';

/**
 * The InlineResponse2001Data model module.
 * @module org.wso2.client.model.OnlineMerchant/InlineResponse2001Data
 * @version 1.0.0
 */
class InlineResponse2001Data {
    /**
     * Constructs a new <code>InlineResponse2001Data</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/InlineResponse2001Data
     */
    constructor() { 
        
        InlineResponse2001Data.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001Data</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001Data} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001Data} The populated <code>InlineResponse2001Data</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001Data();

            if (data.hasOwnProperty('qrdata')) {
                obj['qrdata'] = ApiClient.convertToType(data['qrdata'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('fees')) {
                obj['fees'] = InlineResponse2001DataFees.constructFromObject(data['fees']);
            }
            if (data.hasOwnProperty('referenceNumber')) {
                obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
            }
            if (data.hasOwnProperty('externalTransactionId')) {
                obj['externalTransactionId'] = ApiClient.convertToType(data['externalTransactionId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} qrdata
 */
InlineResponse2001Data.prototype['qrdata'] = undefined;

/**
 * @member {String} amount
 */
InlineResponse2001Data.prototype['amount'] = undefined;

/**
 * @member {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees} fees
 */
InlineResponse2001Data.prototype['fees'] = undefined;

/**
 * @member {String} referenceNumber
 */
InlineResponse2001Data.prototype['referenceNumber'] = undefined;

/**
 * @member {String} externalTransactionId
 */
InlineResponse2001Data.prototype['externalTransactionId'] = undefined;

/**
 * @member {Number} status
 */
InlineResponse2001Data.prototype['status'] = undefined;






export default InlineResponse2001Data;

