/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001DataFees model module.
 * @module org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees
 * @version 1.0.0
 */
class InlineResponse2001DataFees {
    /**
     * Constructs a new <code>InlineResponse2001DataFees</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees
     */
    constructor() { 
        
        InlineResponse2001DataFees.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001DataFees</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees} The populated <code>InlineResponse2001DataFees</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001DataFees();

            if (data.hasOwnProperty('debitFee')) {
                obj['debitFee'] = ApiClient.convertToType(data['debitFee'], 'Number');
            }
            if (data.hasOwnProperty('creditFee')) {
                obj['creditFee'] = ApiClient.convertToType(data['creditFee'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} debitFee
 */
InlineResponse2001DataFees.prototype['debitFee'] = undefined;

/**
 * @member {Number} creditFee
 */
InlineResponse2001DataFees.prototype['creditFee'] = undefined;






export default InlineResponse2001DataFees;

