/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject2 model module.
 * @module org.wso2.client.model.OnlineMerchant/InlineObject2
 * @version 1.0.0
 */
class InlineObject2 {
    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/InlineObject2
     * @param amount {String} 
     * @param externalTransactionId {String} 
     * @param currency {String} 
     * @param customerPhone {String} 
     */
    constructor(amount, externalTransactionId, currency, customerPhone) { 
        
        InlineObject2.initialize(this, amount, externalTransactionId, currency, customerPhone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, externalTransactionId, currency, customerPhone) { 
        obj['amount'] = amount;
        obj['externalTransactionId'] = externalTransactionId;
        obj['currency'] = currency;
        obj['customerPhone'] = customerPhone;
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineObject2} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('externalTransactionId')) {
                obj['externalTransactionId'] = ApiClient.convertToType(data['externalTransactionId'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('customerPhone')) {
                obj['customerPhone'] = ApiClient.convertToType(data['customerPhone'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('externalAdditionalData')) {
                obj['externalAdditionalData'] = ApiClient.convertToType(data['externalAdditionalData'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} amount
 */
InlineObject2.prototype['amount'] = undefined;

/**
 * @member {String} externalTransactionId
 */
InlineObject2.prototype['externalTransactionId'] = undefined;

/**
 * @member {String} currency
 */
InlineObject2.prototype['currency'] = undefined;

/**
 * @member {String} customerPhone
 */
InlineObject2.prototype['customerPhone'] = undefined;

/**
 * @member {String} message
 */
InlineObject2.prototype['message'] = undefined;

/**
 * @member {String} externalAdditionalData
 */
InlineObject2.prototype['externalAdditionalData'] = undefined;






export default InlineObject2;

