/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200Token from './InlineResponse200Token';

/**
 * The InlineResponse200 model module.
 * @module org.wso2.client.model.OnlineMerchant/InlineResponse200
 * @version 1.0.0
 */
class InlineResponse200 {
    /**
     * Constructs a new <code>InlineResponse200</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/InlineResponse200
     */
    constructor() { 
        
        InlineResponse200.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineResponse200} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/InlineResponse200} The populated <code>InlineResponse200</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();

            if (data.hasOwnProperty('err')) {
                obj['err'] = ApiClient.convertToType(data['err'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = InlineResponse200Token.constructFromObject(data['token']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} err
 */
InlineResponse200.prototype['err'] = undefined;

/**
 * @member {String} message
 */
InlineResponse200.prototype['message'] = undefined;

/**
 * @member {module:org.wso2.client.model.OnlineMerchant/InlineResponse200Token} token
 */
InlineResponse200.prototype['token'] = undefined;






export default InlineResponse200;

