/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OmPaymentCodeResultData model module.
 * @module org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData
 * @version 1.0.0
 */
class OmPaymentCodeResultData {
    /**
     * Constructs a new <code>OmPaymentCodeResultData</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData
     */
    constructor() { 
        
        OmPaymentCodeResultData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OmPaymentCodeResultData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData} The populated <code>OmPaymentCodeResultData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OmPaymentCodeResultData();

            if (data.hasOwnProperty('qrdata')) {
                obj['qrdata'] = ApiClient.convertToType(data['qrdata'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('referenceNumber')) {
                obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} qrdata
 */
OmPaymentCodeResultData.prototype['qrdata'] = undefined;

/**
 * @member {String} amount
 */
OmPaymentCodeResultData.prototype['amount'] = undefined;

/**
 * @member {String} referenceNumber
 */
OmPaymentCodeResultData.prototype['referenceNumber'] = undefined;

/**
 * @member {String} status
 */
OmPaymentCodeResultData.prototype['status'] = undefined;






export default OmPaymentCodeResultData;

