/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OmPaymentCodeBody model module.
 * @module org.wso2.client.model.OnlineMerchant/OmPaymentCodeBody
 * @version 1.0.0
 */
class OmPaymentCodeBody {
    /**
     * Constructs a new <code>OmPaymentCodeBody</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeBody
     * @param amount {String} 
     * @param externalTransactionId {String} 
     * @param currency {String} 
     */
    constructor(amount, externalTransactionId, currency) { 
        
        OmPaymentCodeBody.initialize(this, amount, externalTransactionId, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, externalTransactionId, currency) { 
        obj['amount'] = amount;
        obj['externalTransactionId'] = externalTransactionId;
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>OmPaymentCodeBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeBody} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeBody} The populated <code>OmPaymentCodeBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OmPaymentCodeBody();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('externalTransactionId')) {
                obj['externalTransactionId'] = ApiClient.convertToType(data['externalTransactionId'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} amount
 */
OmPaymentCodeBody.prototype['amount'] = undefined;

/**
 * @member {String} externalTransactionId
 */
OmPaymentCodeBody.prototype['externalTransactionId'] = undefined;

/**
 * @member {String} currency
 */
OmPaymentCodeBody.prototype['currency'] = undefined;






export default OmPaymentCodeBody;

