/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OmPaymentCodeResultData from './OmPaymentCodeResultData';

/**
 * The OmPaymentCodeResult model module.
 * @module org.wso2.client.model.OnlineMerchant/OmPaymentCodeResult
 * @version 1.0.0
 */
class OmPaymentCodeResult {
    /**
     * Constructs a new <code>OmPaymentCodeResult</code>.
     * @alias module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResult
     */
    constructor() { 
        
        OmPaymentCodeResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OmPaymentCodeResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResult} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResult} The populated <code>OmPaymentCodeResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OmPaymentCodeResult();

            if (data.hasOwnProperty('err')) {
                obj['err'] = ApiClient.convertToType(data['err'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = OmPaymentCodeResultData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} err
 */
OmPaymentCodeResult.prototype['err'] = undefined;

/**
 * @member {String} message
 */
OmPaymentCodeResult.prototype['message'] = undefined;

/**
 * @member {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData} data
 */
OmPaymentCodeResult.prototype['data'] = undefined;






export default OmPaymentCodeResult;

