/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject from '../org.wso2.client.model.OnlineMerchant/InlineObject';
import InlineResponse200 from '../org.wso2.client.model.OnlineMerchant/InlineResponse200';

/**
* Login service.
* @module org.wso2.client.api.OnlineMerchant/LoginApi
* @version 1.0.0
*/
export default class LoginApi {

    /**
    * Constructs a new LoginApi. 
    * @alias module:org.wso2.client.api.OnlineMerchant/LoginApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the thirdpartyMerchantLoginPost operation.
     * @callback module:org.wso2.client.api.OnlineMerchant/LoginApi~thirdpartyMerchantLoginPostCallback
     * @param {String} error Error message, if any.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineResponse200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Login
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineObject} body 
     * @param {module:org.wso2.client.api.OnlineMerchant/LoginApi~thirdpartyMerchantLoginPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:org.wso2.client.model.OnlineMerchant/InlineResponse200}
     */
    thirdpartyMerchantLoginPost(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling thirdpartyMerchantLoginPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = InlineResponse200;
      return this.apiClient.callApi(
        '/thirdparty/merchant/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
