/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject2 from '../org.wso2.client.model.OnlineMerchant/InlineObject2';
import InlineResponse2002 from '../org.wso2.client.model.OnlineMerchant/InlineResponse2002';

/**
* PaymentPush service.
* @module org.wso2.client.api.OnlineMerchant/PaymentPushApi
* @version 1.0.0
*/
export default class PaymentPushApi {

    /**
    * Constructs a new PaymentPushApi. 
    * @alias module:org.wso2.client.api.OnlineMerchant/PaymentPushApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the thirdpartyMerchantRequestPushPaymentPost operation.
     * @callback module:org.wso2.client.api.OnlineMerchant/PaymentPushApi~thirdpartyMerchantRequestPushPaymentPostCallback
     * @param {String} error Error message, if any.
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Request payment push
     * @param {String} authorization 
     * @param {module:org.wso2.client.model.OnlineMerchant/InlineObject2} body 
     * @param {module:org.wso2.client.api.OnlineMerchant/PaymentPushApi~thirdpartyMerchantRequestPushPaymentPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:org.wso2.client.model.OnlineMerchant/InlineResponse2002}
     */
    thirdpartyMerchantRequestPushPaymentPost(authorization, body, callback) {
      let postBody = body;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling thirdpartyMerchantRequestPushPaymentPost");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling thirdpartyMerchantRequestPushPaymentPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'Authorization': authorization
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = InlineResponse2002;
      return this.apiClient.callApi(
        '/thirdparty/merchant/requestPushPayment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
