/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OnlineMerchant);
  }
}(this, function(expect, OnlineMerchant) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OnlineMerchant.InlineObject2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject2', function() {
    it('should create an instance of InlineObject2', function() {
      // uncomment below and update the code to test InlineObject2
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be.a(OnlineMerchant.InlineObject2);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property externalTransactionId (base name: "externalTransactionId")', function() {
      // uncomment below and update the code to test the property externalTransactionId
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property customerPhone (base name: "customerPhone")', function() {
      // uncomment below and update the code to test the property customerPhone
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property externalAdditionalData (base name: "externalAdditionalData")', function() {
      // uncomment below and update the code to test the property externalAdditionalData
      //var instane = new OnlineMerchant.InlineObject2();
      //expect(instance).to.be();
    });

  });

}));
