/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OnlineMerchant);
  }
}(this, function(expect, OnlineMerchant) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OnlineMerchant.InlineResponse200Token();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse200Token', function() {
    it('should create an instance of InlineResponse200Token', function() {
      // uncomment below and update the code to test InlineResponse200Token
      //var instane = new OnlineMerchant.InlineResponse200Token();
      //expect(instance).to.be.a(OnlineMerchant.InlineResponse200Token);
    });

    it('should have the property expiredAt (base name: "expiredAt")', function() {
      // uncomment below and update the code to test the property expiredAt
      //var instane = new OnlineMerchant.InlineResponse200Token();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instane = new OnlineMerchant.InlineResponse200Token();
      //expect(instance).to.be();
    });

  });

}));
