/**
 * Online merchant
 * API For Online Merchant
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@ayainnovation.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import InlineObject from './org.wso2.client.model.OnlineMerchant/InlineObject';
import InlineObject1 from './org.wso2.client.model.OnlineMerchant/InlineObject1';
import InlineObject2 from './org.wso2.client.model.OnlineMerchant/InlineObject2';
import InlineObject3 from './org.wso2.client.model.OnlineMerchant/InlineObject3';
import InlineResponse200 from './org.wso2.client.model.OnlineMerchant/InlineResponse200';
import InlineResponse2001 from './org.wso2.client.model.OnlineMerchant/InlineResponse2001';
import InlineResponse2001Data from './org.wso2.client.model.OnlineMerchant/InlineResponse2001Data';
import InlineResponse2001DataFees from './org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees';
import InlineResponse2002 from './org.wso2.client.model.OnlineMerchant/InlineResponse2002';
import InlineResponse200Token from './org.wso2.client.model.OnlineMerchant/InlineResponse200Token';
import OmPaymentCodeBody from './org.wso2.client.model.OnlineMerchant/OmPaymentCodeBody';
import OmPaymentCodeResult from './org.wso2.client.model.OnlineMerchant/OmPaymentCodeResult';
import OmPaymentCodeResultData from './org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData';
import LoginApi from './org.wso2.client.api.OnlineMerchant/LoginApi';
import PaymentPushApi from './org.wso2.client.api.OnlineMerchant/PaymentPushApi';
import QRCodeApi from './org.wso2.client.api.OnlineMerchant/QRCodeApi';
import RefundApi from './org.wso2.client.api.OnlineMerchant/RefundApi';


/**
* API_For_Online_Merchant.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OnlineMerchant = require('index'); // See note below*.
* var xxxSvc = new OnlineMerchant.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OnlineMerchant.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OnlineMerchant.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OnlineMerchant.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The InlineObject model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2001Data model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001Data}
     */
    InlineResponse2001Data,

    /**
     * The InlineResponse2001DataFees model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineResponse2001DataFees}
     */
    InlineResponse2001DataFees,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse200Token model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/InlineResponse200Token}
     */
    InlineResponse200Token,

    /**
     * The OmPaymentCodeBody model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeBody}
     */
    OmPaymentCodeBody,

    /**
     * The OmPaymentCodeResult model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResult}
     */
    OmPaymentCodeResult,

    /**
     * The OmPaymentCodeResultData model constructor.
     * @property {module:org.wso2.client.model.OnlineMerchant/OmPaymentCodeResultData}
     */
    OmPaymentCodeResultData,

    /**
    * The LoginApi service constructor.
    * @property {module:org.wso2.client.api.OnlineMerchant/LoginApi}
    */
    LoginApi,

    /**
    * The PaymentPushApi service constructor.
    * @property {module:org.wso2.client.api.OnlineMerchant/PaymentPushApi}
    */
    PaymentPushApi,

    /**
    * The QRCodeApi service constructor.
    * @property {module:org.wso2.client.api.OnlineMerchant/QRCodeApi}
    */
    QRCodeApi,

    /**
    * The RefundApi service constructor.
    * @property {module:org.wso2.client.api.OnlineMerchant/RefundApi}
    */
    RefundApi
};
